//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/hecto/RiderProjects/BRAQ/BRAQ_grammar\BRAQLexer.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class BRAQLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQUALS=1, PLUS=2, MINUS=3, STAR=4, SLASH=5, MODULUS=6, AT_OPERATOR=7, 
		GR=8, GE=9, LS=10, LE=11, EQ=12, NE=13, AND=14, OR=15, XOR=16, NOT=17, 
		NUMBER=18, DOUBLE_NUMBER=19, LBRACKET=20, RBRACKET=21, LCURLY=22, RCURLY=23, 
		SEMICOLON=24, NEWLINE=25, SPACE=26, VAR=27, PRINT=28, READ=29, IF=30, 
		ELSE=31, STRING=32, ID=33;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"EQUALS", "PLUS", "MINUS", "STAR", "SLASH", "MODULUS", "AT_OPERATOR", 
		"GR", "GE", "LS", "LE", "EQ", "NE", "AND", "OR", "XOR", "NOT", "NUMBER", 
		"DOUBLE_NUMBER", "LBRACKET", "RBRACKET", "LCURLY", "RCURLY", "SEMICOLON", 
		"NEWLINE", "SPACE", "VAR", "PRINT", "READ", "IF", "ELSE", "STRING", "ID"
	};


	public BRAQLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public BRAQLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'+'", "'-'", "'*'", "'/'", "'%'", "'@'", "'>'", "'>='", 
		"'<'", "'<='", "'?='", "'!='", "'and'", "'or'", "'xor'", "'not'", null, 
		null, "'('", "')'", "'{'", "'}'", "';'", null, null, "'var'", "'print'", 
		"'read'", "'if'", "'else'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQUALS", "PLUS", "MINUS", "STAR", "SLASH", "MODULUS", "AT_OPERATOR", 
		"GR", "GE", "LS", "LE", "EQ", "NE", "AND", "OR", "XOR", "NOT", "NUMBER", 
		"DOUBLE_NUMBER", "LBRACKET", "RBRACKET", "LCURLY", "RCURLY", "SEMICOLON", 
		"NEWLINE", "SPACE", "VAR", "PRINT", "READ", "IF", "ELSE", "STRING", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BRAQLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static BRAQLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '#', '\xC1', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x6', '\x13', 
		't', '\n', '\x13', '\r', '\x13', '\xE', '\x13', 'u', '\x3', '\x14', '\x6', 
		'\x14', 'y', '\n', '\x14', '\r', '\x14', '\xE', '\x14', 'z', '\x3', '\x14', 
		'\x3', '\x14', '\x6', '\x14', '\x7F', '\n', '\x14', '\r', '\x14', '\xE', 
		'\x14', '\x80', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x1A', '\x6', '\x1A', '\x8E', '\n', '\x1A', '\r', 
		'\x1A', '\xE', '\x1A', '\x8F', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', 
		'\x6', '\x1B', '\x95', '\n', '\x1B', '\r', '\x1B', '\xE', '\x1B', '\x96', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x3', '!', '\a', '!', '\xB4', '\n', '!', '\f', '!', '\xE', '!', '\xB7', 
		'\v', '!', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\a', '\"', 
		'\xBD', '\n', '\"', '\f', '\"', '\xE', '\"', '\xC0', '\v', '\"', '\x3', 
		'\xB5', '\x2', '#', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', 
		'\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', 
		'+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', 
		'\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', 
		'?', '!', '\x41', '\"', '\x43', '#', '\x3', '\x2', '\a', '\x3', '\x2', 
		'\x32', ';', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x4', '\x2', '\v', 
		'\v', '\"', '\"', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x2', '\xC7', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x45', '\x3', '\x2', '\x2', '\x2', '\x5', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\a', 'I', '\x3', '\x2', '\x2', '\x2', '\t', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\v', 'M', '\x3', '\x2', '\x2', '\x2', '\r', 'O', 
		'\x3', '\x2', '\x2', '\x2', '\xF', 'Q', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'S', '\x3', '\x2', '\x2', '\x2', '\x13', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'X', '\x3', '\x2', '\x2', '\x2', '\x17', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\x19', ']', '\x3', '\x2', '\x2', '\x2', '\x1B', '`', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x63', '\x3', '\x2', '\x2', '\x2', '\x1F', 'g', 
		'\x3', '\x2', '\x2', '\x2', '!', 'j', '\x3', '\x2', '\x2', '\x2', '#', 
		'n', '\x3', '\x2', '\x2', '\x2', '%', 's', '\x3', '\x2', '\x2', '\x2', 
		'\'', 'x', '\x3', '\x2', '\x2', '\x2', ')', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x84', '\x3', '\x2', '\x2', '\x2', '-', '\x86', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x88', '\x3', '\x2', '\x2', '\x2', '\x31', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x94', '\x3', '\x2', '\x2', '\x2', '\x37', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\x9E', '\x3', '\x2', '\x2', '\x2', ';', '\xA4', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xA9', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\x41', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xBA', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', 
		'?', '\x2', '\x2', '\x46', '\x4', '\x3', '\x2', '\x2', '\x2', 'G', 'H', 
		'\a', '-', '\x2', '\x2', 'H', '\x6', '\x3', '\x2', '\x2', '\x2', 'I', 
		'J', '\a', '/', '\x2', '\x2', 'J', '\b', '\x3', '\x2', '\x2', '\x2', 'K', 
		'L', '\a', ',', '\x2', '\x2', 'L', '\n', '\x3', '\x2', '\x2', '\x2', 'M', 
		'N', '\a', '\x31', '\x2', '\x2', 'N', '\f', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', '\'', '\x2', '\x2', 'P', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '\x42', '\x2', '\x2', 'R', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '@', '\x2', '\x2', 'T', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '@', '\x2', '\x2', 'V', 'W', '\a', '?', '\x2', 
		'\x2', 'W', '\x14', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\a', '>', '\x2', 
		'\x2', 'Y', '\x16', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '>', '\x2', 
		'\x2', '[', '\\', '\a', '?', '\x2', '\x2', '\\', '\x18', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\a', '\x41', '\x2', '\x2', '^', '_', '\a', '?', 
		'\x2', '\x2', '_', '\x1A', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', 
		'#', '\x2', '\x2', '\x61', '\x62', '\a', '?', '\x2', '\x2', '\x62', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', '\x63', '\x2', '\x2', 
		'\x64', '\x65', '\a', 'p', '\x2', '\x2', '\x65', '\x66', '\a', '\x66', 
		'\x2', '\x2', '\x66', '\x1E', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 
		'q', '\x2', '\x2', 'h', 'i', '\a', 't', '\x2', '\x2', 'i', ' ', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'k', '\a', 'z', '\x2', '\x2', 'k', 'l', '\a', 
		'q', '\x2', '\x2', 'l', 'm', '\a', 't', '\x2', '\x2', 'm', '\"', '\x3', 
		'\x2', '\x2', '\x2', 'n', 'o', '\a', 'p', '\x2', '\x2', 'o', 'p', '\a', 
		'q', '\x2', '\x2', 'p', 'q', '\a', 'v', '\x2', '\x2', 'q', '$', '\x3', 
		'\x2', '\x2', '\x2', 'r', 't', '\t', '\x2', '\x2', '\x2', 's', 'r', '\x3', 
		'\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', '\x2', '\x2', 'u', 's', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', '&', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'y', '\t', '\x2', '\x2', '\x2', 'x', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', 
		'\x2', '\x2', '\x2', '|', '~', '\a', '\x30', '\x2', '\x2', '}', '\x7F', 
		'\t', '\x2', '\x2', '\x2', '~', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x80', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '(', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\a', '*', '\x2', '\x2', '\x83', 
		'*', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '+', '\x2', '\x2', 
		'\x85', ',', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', '}', '\x2', 
		'\x2', '\x87', '.', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 
		'\x7F', '\x2', '\x2', '\x89', '\x30', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', '=', '\x2', '\x2', '\x8B', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8E', '\t', '\x3', '\x2', '\x2', '\x8D', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\b', 
		'\x1A', '\x2', '\x2', '\x92', '\x34', '\x3', '\x2', '\x2', '\x2', '\x93', 
		'\x95', '\t', '\x4', '\x2', '\x2', '\x94', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\b', '\x1B', '\x2', 
		'\x2', '\x99', '\x36', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\a', 
		'x', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x63', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', 't', '\x2', '\x2', '\x9D', '\x38', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\a', 'r', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		't', '\x2', '\x2', '\xA0', '\xA1', '\a', 'k', '\x2', '\x2', '\xA1', '\xA2', 
		'\a', 'p', '\x2', '\x2', '\xA2', '\xA3', '\a', 'v', '\x2', '\x2', '\xA3', 
		':', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', 't', '\x2', '\x2', 
		'\xA5', '\xA6', '\a', 'g', '\x2', '\x2', '\xA6', '\xA7', '\a', '\x63', 
		'\x2', '\x2', '\xA7', '\xA8', '\a', '\x66', '\x2', '\x2', '\xA8', '<', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\a', 'k', '\x2', '\x2', '\xAA', 
		'\xAB', '\a', 'h', '\x2', '\x2', '\xAB', '>', '\x3', '\x2', '\x2', '\x2', 
		'\xAC', '\xAD', '\a', 'g', '\x2', '\x2', '\xAD', '\xAE', '\a', 'n', '\x2', 
		'\x2', '\xAE', '\xAF', '\a', 'u', '\x2', '\x2', '\xAF', '\xB0', '\a', 
		'g', '\x2', '\x2', '\xB0', '@', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB5', 
		'\a', '$', '\x2', '\x2', '\xB2', '\xB4', '\v', '\x2', '\x2', '\x2', '\xB3', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\a', '$', '\x2', 
		'\x2', '\xB9', '\x42', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBE', '\t', 
		'\x5', '\x2', '\x2', '\xBB', '\xBD', '\t', '\x6', '\x2', '\x2', '\xBC', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\x44', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', 'u', 'z', '\x80', '\x8F', 
		'\x96', '\xB5', '\xBE', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
