//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/hecto/RiderProjects/BRAQ/BRAQ_grammar\BRAQParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBRAQParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class BRAQParserBaseListener : IBRAQParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] BRAQParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] BRAQParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] BRAQParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] BRAQParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_stmt_base([NotNull] BRAQParser.Var_stmt_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_stmt_base([NotNull] BRAQParser.Var_stmt_baseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.print_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_stmt_base([NotNull] BRAQParser.Print_stmt_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.print_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_stmt_base([NotNull] BRAQParser.Print_stmt_baseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.assign_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_stmt_base([NotNull] BRAQParser.Assign_stmt_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.assign_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_stmt_base([NotNull] BRAQParser.Assign_stmt_baseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.read_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRead_stmt_base([NotNull] BRAQParser.Read_stmt_baseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.read_stmt_base"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRead_stmt_base([NotNull] BRAQParser.Read_stmt_baseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] BRAQParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] BRAQParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup([NotNull] BRAQParser.GroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup([NotNull] BRAQParser.GroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] BRAQParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] BRAQParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg_list([NotNull] BRAQParser.Arg_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg_list([NotNull] BRAQParser.Arg_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] BRAQParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] BRAQParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_node([NotNull] BRAQParser.Var_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_node([NotNull] BRAQParser.Var_nodeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
