//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/hecto/RiderProjects/BRAQ/BRAQ_grammar\BRAQParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BRAQParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IBRAQParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] BRAQParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] BRAQParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] BRAQParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] BRAQParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] BRAQParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] BRAQParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] BRAQParser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] BRAQParser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_stmt_base([NotNull] BRAQParser.Var_stmt_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_stmt_base([NotNull] BRAQParser.Var_stmt_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.print_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_stmt_base([NotNull] BRAQParser.Print_stmt_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.print_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_stmt_base([NotNull] BRAQParser.Print_stmt_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.assign_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_stmt_base([NotNull] BRAQParser.Assign_stmt_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.assign_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_stmt_base([NotNull] BRAQParser.Assign_stmt_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.read_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRead_stmt_base([NotNull] BRAQParser.Read_stmt_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.read_stmt_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRead_stmt_base([NotNull] BRAQParser.Read_stmt_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] BRAQParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] BRAQParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] BRAQParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] BRAQParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] BRAQParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] BRAQParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg_list([NotNull] BRAQParser.Arg_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg_list([NotNull] BRAQParser.Arg_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] BRAQParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] BRAQParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_node([NotNull] BRAQParser.Var_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_node([NotNull] BRAQParser.Var_nodeContext context);
}
