//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/hecto/RiderProjects/BRAQ/BRAQ_grammar\BRAQParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BRAQParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IBRAQParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] BRAQParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] BRAQParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] BRAQParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] BRAQParser.If_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.while_loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_loop_stmt([NotNull] BRAQParser.While_loop_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.var_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_stmt([NotNull] BRAQParser.Var_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_stmt([NotNull] BRAQParser.Expr_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] BRAQParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] BRAQParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.logical_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_or([NotNull] BRAQParser.Logical_orContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.logical_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_xor([NotNull] BRAQParser.Logical_xorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_and([NotNull] BRAQParser.Logical_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.logical_equal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_equal([NotNull] BRAQParser.Logical_equalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.logical_gr_le"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_gr_le([NotNull] BRAQParser.Logical_gr_leContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddition([NotNull] BRAQParser.AdditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplication([NotNull] BRAQParser.MultiplicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.unary_not_neg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_not_neg([NotNull] BRAQParser.Unary_not_negContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] BRAQParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.short_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShort_call([NotNull] BRAQParser.Short_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] BRAQParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup([NotNull] BRAQParser.GroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_node([NotNull] BRAQParser.Var_nodeContext context);
}
