//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/hecto/RiderProjects/BRAQ/BRAQ_grammar\BRAQParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBRAQParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class BRAQParserBaseListener : IBRAQParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] BRAQParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] BRAQParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] BRAQParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] BRAQParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] BRAQParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] BRAQParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stmt([NotNull] BRAQParser.If_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stmt([NotNull] BRAQParser.If_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.while_loop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_loop_stmt([NotNull] BRAQParser.While_loop_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.while_loop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_loop_stmt([NotNull] BRAQParser.While_loop_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.function_def_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_def_stmt([NotNull] BRAQParser.Function_def_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.function_def_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_def_stmt([NotNull] BRAQParser.Function_def_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.typed_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTyped_id([NotNull] BRAQParser.Typed_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.typed_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTyped_id([NotNull] BRAQParser.Typed_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak_stmt([NotNull] BRAQParser.Break_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak_stmt([NotNull] BRAQParser.Break_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.continue_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinue_stmt([NotNull] BRAQParser.Continue_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.continue_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinue_stmt([NotNull] BRAQParser.Continue_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_stmt([NotNull] BRAQParser.Return_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_stmt([NotNull] BRAQParser.Return_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_stmt([NotNull] BRAQParser.Var_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_stmt([NotNull] BRAQParser.Var_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.expr_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_stmt([NotNull] BRAQParser.Expr_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.expr_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_stmt([NotNull] BRAQParser.Expr_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] BRAQParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] BRAQParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] BRAQParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] BRAQParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_or([NotNull] BRAQParser.Logical_orContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_or([NotNull] BRAQParser.Logical_orContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_xor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_xor([NotNull] BRAQParser.Logical_xorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_xor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_xor([NotNull] BRAQParser.Logical_xorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_and([NotNull] BRAQParser.Logical_andContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_and([NotNull] BRAQParser.Logical_andContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_equal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_equal([NotNull] BRAQParser.Logical_equalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_equal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_equal([NotNull] BRAQParser.Logical_equalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_gr_le"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogical_gr_le([NotNull] BRAQParser.Logical_gr_leContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_gr_le"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogical_gr_le([NotNull] BRAQParser.Logical_gr_leContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.addition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddition([NotNull] BRAQParser.AdditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.addition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddition([NotNull] BRAQParser.AdditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.multiplication"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplication([NotNull] BRAQParser.MultiplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.multiplication"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplication([NotNull] BRAQParser.MultiplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.unary_not_neg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_not_neg([NotNull] BRAQParser.Unary_not_negContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.unary_not_neg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_not_neg([NotNull] BRAQParser.Unary_not_negContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] BRAQParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] BRAQParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.short_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShort_call([NotNull] BRAQParser.Short_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.short_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShort_call([NotNull] BRAQParser.Short_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] BRAQParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] BRAQParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup([NotNull] BRAQParser.GroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup([NotNull] BRAQParser.GroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_node([NotNull] BRAQParser.Var_nodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_node([NotNull] BRAQParser.Var_nodeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
