//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/hecto/RiderProjects/BRAQ/BRAQ_grammar\BRAQParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BRAQParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IBRAQParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] BRAQParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] BRAQParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] BRAQParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] BRAQParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] BRAQParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] BRAQParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] BRAQParser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] BRAQParser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.while_loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_loop_stmt([NotNull] BRAQParser.While_loop_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.while_loop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_loop_stmt([NotNull] BRAQParser.While_loop_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.function_def_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_def_stmt([NotNull] BRAQParser.Function_def_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.function_def_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_def_stmt([NotNull] BRAQParser.Function_def_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.typed_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyped_id([NotNull] BRAQParser.Typed_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.typed_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyped_id([NotNull] BRAQParser.Typed_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreak_stmt([NotNull] BRAQParser.Break_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreak_stmt([NotNull] BRAQParser.Break_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinue_stmt([NotNull] BRAQParser.Continue_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinue_stmt([NotNull] BRAQParser.Continue_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stmt([NotNull] BRAQParser.Return_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stmt([NotNull] BRAQParser.Return_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_stmt([NotNull] BRAQParser.Var_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_stmt([NotNull] BRAQParser.Var_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_stmt([NotNull] BRAQParser.Expr_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_stmt([NotNull] BRAQParser.Expr_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] BRAQParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] BRAQParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] BRAQParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] BRAQParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_or([NotNull] BRAQParser.Logical_orContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_or([NotNull] BRAQParser.Logical_orContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_xor([NotNull] BRAQParser.Logical_xorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_xor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_xor([NotNull] BRAQParser.Logical_xorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_and([NotNull] BRAQParser.Logical_andContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_and([NotNull] BRAQParser.Logical_andContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_equal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_equal([NotNull] BRAQParser.Logical_equalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_equal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_equal([NotNull] BRAQParser.Logical_equalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.logical_gr_le"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical_gr_le([NotNull] BRAQParser.Logical_gr_leContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.logical_gr_le"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical_gr_le([NotNull] BRAQParser.Logical_gr_leContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddition([NotNull] BRAQParser.AdditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddition([NotNull] BRAQParser.AdditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplication([NotNull] BRAQParser.MultiplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplication([NotNull] BRAQParser.MultiplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.unary_not_neg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_not_neg([NotNull] BRAQParser.Unary_not_negContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.unary_not_neg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_not_neg([NotNull] BRAQParser.Unary_not_negContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.dot_notation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDot_notation([NotNull] BRAQParser.Dot_notationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.dot_notation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDot_notation([NotNull] BRAQParser.Dot_notationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] BRAQParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] BRAQParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.short_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShort_call([NotNull] BRAQParser.Short_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.short_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShort_call([NotNull] BRAQParser.Short_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] BRAQParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] BRAQParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] BRAQParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] BRAQParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_node([NotNull] BRAQParser.Var_nodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BRAQParser.var_node"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_node([NotNull] BRAQParser.Var_nodeContext context);
}
